# Generated by Django 3.0.4 on 2020-05-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200517_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OnShipping', 'OnShipping'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('Prepearing', 'Prepearing'), ('Completed', 'Completed'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
