# Generated by Django 3.0.4 on 2020-05-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200517_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OnShipping', 'OnShipping'), ('New', 'New'), ('Completed', 'Completed'), ('Prepearing', 'Prepearing'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted')], default='New', max_length=10),
        ),
    ]
