# Generated by Django 3.0.4 on 2020-05-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200531_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Canceled', 'Canceled'), ('OnShipping', 'OnShipping'), ('New', 'New'), ('Accepted', 'Accepted'), ('Prepearing', 'Prepearing')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('New', 'New'), ('Accepted', 'Accepted')], default='New', max_length=10),
        ),
    ]
