# Generated by Django 3.0.4 on 2020-05-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200531_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Prepearing', 'Prepearing'), ('New', 'New'), ('Completed', 'Completed'), ('OnShipping', 'OnShipping'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='New', max_length=10),
        ),
    ]
