# Generated by Django 3.0.4 on 2020-05-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200531_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('Prepearing', 'Prepearing'), ('Accepted', 'Accepted'), ('OnShipping', 'OnShipping'), ('Canceled', 'Canceled')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('New', 'New'), ('Canceled', 'Canceled')], default='New', max_length=10),
        ),
    ]
