# Generated by Django 3.0.4 on 2020-05-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200531_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OnShipping', 'OnShipping'), ('New', 'New'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('Prepearing', 'Prepearing'), ('Completed', 'Completed')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Canceled', 'Canceled'), ('New', 'New')], default='New', max_length=10),
        ),
    ]
